
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_KEY: ${API_KEY}
        CLIENT_ID: ${CLIENT_ID}
    environment:
      DATABASE_URL: postgres://your_username:your_password@postgres:5432/your_database?sslmode=disable
      API_KEY: ${API_KEY}
      CLIENT_ID: ${CLIENT_ID}
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  pgdata:
