

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_KEY: ${API_KEY}
        CLIENT_ID: ${CLIENT_ID}
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      API_KEY: ${API_KEY}
      CLIENT_ID: ${CLIENT_ID}
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  pgdata:

#env_file:
 # - .env  # Убедитесь, что .env файл подгружается корректно
